In [1]:
#cleans data and exports it as a csv

In [2]:
import pandas as pd

In [3]:
#download data: https://docs.deistercloud.com/Databases.30/TPCH%20Benchmark.90/Data%20generation%20tool.30.xml?embedded=true
#CUSTOMER = pd.read_table('data/customer.csv', header=None, sep = '|')
LINEITEM = pd.read_table('data/lineitem.tbl', header=None, sep = '|')
NATION = pd.read_table('data/nation.tbl', header=None, sep='|')
ORDERS = pd.read_table('data/orders.tbl', header=None, sep = '|')
PART = pd.read_table('data/part.tbl', header=None, sep = '|')
PARTSUPP = pd.read_table('data/partsupp.tbl', header=None, sep = '|')
REGION = pd.read_table('data/region.tbl', header=None, sep = '|')
SUPPLIER = pd.read_table('data/supplier.tbl', header=None, sep = '|')

In [4]:
#cleaning http://www.tpc.org/tpc_documents_current_versions/pdf/tpc-h_v2.18.0.pdf section 1.4
#remove column of NAs
CUSTOMER = CUSTOMER.iloc[:, :-1]
LINEITEM = LINEITEM.iloc[:, :-1]
NATION = NATION.iloc[:, :-1]
ORDERS = ORDERS.iloc[:, :-1]
PART = PART.iloc[:, :-1]
PARTSUPP = PARTSUPP.iloc[:, :-1]
REGION = REGION.iloc[:, :-1]
SUPPLIER = SUPPLIER.iloc[:, :-1]

In [5]:
#assign column names
CUSTOMER.columns = ['CUSTKEY', 'NAME', 'ADDRESS', 'NATIONKEY', 'PHONE', 'ACCTBAL', 
                    'MKTSEGMENT', 'COMMENT']
LINEITEM.columns = ['ORDERKEY', 'PARTKEY', 'SUPPKEY', 'LINENUMBER', 'QUANTITY', 'EXTENDEDPRICE',
                    'DISCOUNT', 'TAX','RETURNFLAG', 'LINESTATUS', 'SHIPDATE', 'COMMITDATE',
                    'RECEIPTDATE', 'SHIPINSTRUCT', 'SHIPMODE', 'COMMENT']
NATION.columns = ['NATIONKEY', 'NAME', 'REGIONKEY', 'COMMENT']
ORDERS.columns = ['ORDERKEY', 'CUSTKEY', 'ORDERSTATUS', 'TOTALPRICE', 'ORDERDATE', 'ORDERPRIORITY',
                  'CLERK', 'SHIPPRIORITY', 'COMMENT']
PART.columns = ['PARTKEY', 'NAME','MFGR', 'BRAND', 'TYPE', 'SIZE', 'CONTAINER', 'RETAILPRICE', 
               'COMMENT']
PARTSUPP.columns = ['PARTKEY', 'SUPPKEY', 'AVAILQTY', 'SUPPLYCOST', 'COMMENT']
REGION.columns = ['REGIONKEY', 'NAME', 'COMMENT']
SUPPLIER.columns = ['SUPPKEY', 'NAME', 'ADDRESS', 'NATIONKEY', 'PHONE', 'ACCTBAL', 'COMMENT']

In [6]:
#remove comment columns
CUSTOMER = CUSTOMER.drop('COMMENT', axis=1)
LINEITEM = LINEITEM.drop('COMMENT', axis=1)
NATION = NATION.drop('COMMENT', axis=1)
ORDERS = ORDERS.drop('COMMENT', axis=1)
PART = PART.drop('COMMENT', axis=1)
PARTSUPP = PARTSUPP.drop('COMMENT', axis=1)
REGION = REGION.drop('COMMENT', axis=1)
SUPPLIER = SUPPLIER.drop('COMMENT', axis=1)

In [8]:
CUSTOMER

,CUSTKEY,NAME,ADDRESS,NATIONKEY,PHONE,ACCTBAL,MKTSEGMENT
0,1,Customer#000000001,"IVhzIApeRb ot,c,E",15,25-989-741-2988,711.56,BUILDING
1,2,Customer#000000002,"XSTf4,NCwDVaWNe6tEgvwfmRchLXak",13,23-768-687-3665,121.65,AUTOMOBILE
2,3,Customer#000000003,MG9kdTD2WBHm,1,11-719-748-3364,7498.12,AUTOMOBILE
3,4,Customer#000000004,XxVSJsLAGtn,4,14-128-190-5944,2866.83,MACHINERY
4,5,Customer#000000005,KvpyuHCplrB84WgAiGV6sYpZq7Tj,3,13-750-942-6364,794.47,HOUSEHOLD
...,...,...,...,...,...,...,...
149995,149996,Customer#000149996,syg3m0h2HMEUY6zJ2GEVMKkBl,10,20-149-234-3062,8524.71,AUTOMOBILE
149996,149997,Customer#000149997,ufK xSg6NRC8QaunPB7J,21,31-694-123-5061,8936.21,MACHINERY
149997,149998,Customer#000149998,"NaDi,1fCNPDTntnVUjGyUJ8TrlIeYNK7v",2,12-860-414-6024,5952.41,BUILDING
149998,149999,Customer#000149999,nBpZoYhCPFKZqSunxdeHtRN08x3RE8hqh,1,11-401-828-7411,6104.03,AUTOMOBILE
149999,150000,Customer#000150000,DD7m6OBUJqlbTpiYmzK9SYuJBG266UKoAsKH,10,20-354-401-2016,2530.68,AUTOMOBILE

In [ ]:
#export as csv
CUSTOMER.to_csv('data/customer_clean.csv')
LINEITEM.to_csv('data/lineitem_clean.csv')
NATION.to_csv('data/nation_clean.csv')
ORDERS.to_csv('data/orders_clean.csv')
PART.to_csv('data/part_clean.csv')
PARTSUPP.to_csv('data/partsupp_clean.csv')
REGION.to_csv('data/region_clean.csv')
SUPPLIER.to_csv('data/supplier_clean.csv')

In [7]:
#merge
merged_data = pd.merge(CUSTOMER, LINEITEM, NATION, ORDERS, PART, PARTSUPP, REGION, SUPPLIER)

ValueError: left_index parameter must be of type bool, not <class 'pandas.core.frame.DataFrame'>